server:
  port: 8004
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flymecode/config-mx
          username: xxx
          password: xxx
  rabbitmq:
    host: 120.79.7.246
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    server-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
