server:
  port: 8001

eureka:
  instance:
    hostname: product-server
  client:
    server-url:
      defaultZone: http://localhost:8671/eureka/

spring:
  application:
    name: product-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.79.7.246:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
