server:
  port: 8003

spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.79.7.246:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


eureka:
  instance:
    ip-address: ${spring.cloud.client.ip-address}:${server.port}
  client:
    server-url:
      defaultZone: http://localhost:8671/eureka/

