server:
  port: 8001

eureka:
#  instance:
#    ip-address: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    server-url:
      defaultZone: http://localhost:8671/eureka/

spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.79.7.246:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
